### ISSUE TITLE
enable sharding

### ISSUE THREAD

**Issue by i10416** [Nikkei/imgix_core_dart#8]
see https://github.com/imgix/imgix-blueprint/issues/1

**Comment by sherwinski** [comment]
Hello @i10416 👋
I wanted to point out that domain sharding was deprecated and removed from all of our official libraries some years ago, so you may want to reconsider introducing it to this library. Here is an [example of a PR](https://github.com/imgix/imgix-rb/pull/46) to remove the deprecated feature from our ruby SDK and our [blog post](https://blog.imgix.com/2019/05/03/deprecating-domain-sharding) talking about our decision against domain sharding. Hope that this is helpful!
